### ISSUE TITLE
Three examples and TypeScript

### ISSUE THREAD

**Issue by jdanylko** [jdanylko/Tuxboard#12]
Hey everyone,

What better way to start an August month but with new changes to a repository.

It has been a while (pandemics will do that), but I wanted to catch everybody up on the latest changes.

1. Last night, I merged the TypeScript into the master.

2. I've created three examples with three approaches:
  - StaticDashboard - The simplest dashboard with static content for non-user dashboards (Razor Pages)
  - UserSpecificDashboard - a user-specific dashboard (ASP.NET 5 MVC)
  - UserDashboard - Another user-specific dashboard (ASP.NET Razor Pages w/ MS Identity).

**NOTE:** The examples are now using npm and the Task Runner. In Visual Studio, right-click on each packages.json to "Restore Packages" before running. I've tried to include everything in the Task Runner to make it run effortlessly.

3. In my examples, I'm using TypeScript instead of vanilla JavaScript. While I'm not the best UI designer, these examples are NOT to be packaged into this library. THEY ARE ONLY MEANT AS EXAMPLES. The star of this repository is the Tuxboard.Core and this is what will be packaged and NuGet'ed/distributed.

My plans moving forward with this repository include:
   * <strike>Complete the NuGet packaging so it's automated</strike>
   * Finish the Wiki documentation
   * Answer any questions
   * (possibly) Create a website for the library using [GitHub Pages](https://pages.github.com/).

If you have any comments, complaints, (or stars you want to click), please let me know.

JD

**Comment by papyr** [comment]
Hello have you seen the new ASP 6 release, do you reckon it would help us, anything we can leverage for tux

**Comment by fasteddys** [comment]
Your design is very impressive, is there any explanation around it. I want to get good at it, see if I can contribute some samples. Where do I start,  and how to set it up. Can we do a Hospital Management System or Some a HOA or something that would make sense.
