### ISSUE TITLE
Suggestion Rename Tuxboard to something more catchy

### ISSUE THREAD

**Issue by weedkiller** [jdanylko/Tuxboard#13]
Hello, we should consider renaming Tuxboard to something more catch.

For e.g. something like...
### _...Core Dynamic_ Dashboards

**Comment by jdanylko** [comment]
The naming was a one-day idea that just popped into my head when I was looking for a name with some type of branding.

"Core Dynamic Dashboards" doesn't quite roll off the tongue. :-)

**Comment by weedkiller** [comment]
You have a point, we need something that sticks & conveys its a dashboard, any ideas..
