### ISSUE TITLE
NuGet Packages Available

### ISSUE THREAD

**Issue by jdanylko** [jdanylko/Tuxboard#15]
Version 1.2.0 is now available on NuGet.

I've also updated the Quick Start to create a VERY simple Dashboard from scratch (one widget, that's it!). It's similar to the Static Dashboard.

If you are looking for a more detailed example, check either the [UserDashboard](https://github.com/jdanylko/Tuxboard/tree/master/UserDashboard) or the [UserSpecificDashboard](https://github.com/jdanylko/Tuxboard/tree/master/UserSpecificDashboard).

I'll be updating the wiki and provide more examples on my blog soon.

**Comment by weedkiller** [comment]
Hello Dan, can you please share .NET Core  7 / 6

**Comment by jdanylko** [comment]
> 

I just pushed out .NET 6.0 (along w/ 5.0)
