### ISSUE TITLE
How to setup User driven options for the widget 

### ISSUE THREAD

**Issue by weedkiller** [jdanylko/Tuxboard#2]
Hello this is fantastic 🥇 its such a common need yet ASP MS team is always behind.

Is it ok if I recommend some features like widget configuration, data permissions.

We need some good examples on extending the widget to let user do business specific configuration for their views.

- [ ] Configurable User Driven Widgets/Panels/Charts
- [ ] Let the user choose, the Data Sources/Tables to those Charts
- [ ] Let the user modify Label Names, like X axis and Y Axisi
- [ ] Let the user create a formula or KPI (like a formula)

Hello, I added this as a suggestion and it was lost and slowly keeps getting lost to the bottom of the pile.

We need some good examples on creating 

- Configurable User Driven Widgets/Panels/Charts
- Let the user choose, the Data Sources/Tables to those Charts
- Let the user modify Label Names, like X axis and Y Axisi
- Let the user create a formula or KPI

https://github.com/aspnetzero/aspnet-zero-core/issues/2809#issuecomment-561309329

In summary
__________________________

Sorry about the crude drawings,

- **Dashboard** _global_ settings vs _instance_ settings e.g. only 
  [SquareUp sample](https://squareup.com/help/us/en/article/5183-square-dashboard-overview)

- **Widgets** **Global settings** configured for the tenant level vs. instance settings that are used/set by user when he is viewing
          - I was referring to the widget settings, many people will have different types of widgets they will develop, and will want to render data based on user actions like 1) which widget did he pick, 2) did he use the default setting or change the other settings. 
         - For e.g. global setting are like, export to jpeg, excel, lock unlock. You can display user specific setting below the global settings 

Capture user and global settings in one place on the gear icon
![image](https://user-images.githubusercontent.com/21086190/70079680-32a24700-15d3-11ea-97ef-71fd32e6d451.png)

Also allow the widget to o be updated _without refreshing entire page_

_________________________________

Samples of **charts** on Github free [eCharts](https://echarts.apache.org/examples/en/)
![image](https://user-images.githubusercontent.com/21086190/78740120-e883f600-7923-11ea-914f-a50dff8f2911.png)

________________

[Setting up **KPI on a widget**](https://www.manageengine.com/analytics-plus/help/dashboard/kpi-widgets.html)

**Comment by jdanylko** [comment]
First, thank you soooo much for this "issue." These are the kind of issues I like.

You are definitely most welcome to request features. 

As a matter of fact,

- Everything you've mentioned has been achieved through this framework in one way or another.
- I am expanding my site to dedicate a entire section to Tuxboard with tutorials and posts on how to expand the framework to meet your dashboard needs.

While I haven't had time with my full-time job and other commitments, I am dedicated to this project.

Stay tuned (and thank you soooo much for

**Comment by weedkiller** [comment]
Sorry, there is no way for me to mark it as a feature or suggestion. This is a feature suggestion!!

If you get it to a portal level template, it would be nice to have an affordable commercial license as well. 

Is it free to use, also are you on discord ghangouts or some form of chat.
