### ISSUE TITLE
how to integrate with existing project

### ISSUE THREAD

**Issue by reach2rv** [jdanylko/Tuxboard#3]
Hi,

Thank you for the great work. I really appreciate your efforts to create this project. I have an existing project in asp.net core and i am looking forward to integrate this dashboard with the scope of current project. Can you please provide some insight how it can be achieved. 

I have tried by coping required cshtml, css and js files but on load I get following error;

```JavaScript
Uncaught TypeError: Cannot read property 'getElementsByClassName' of null
    at getDashboardColumns (tuxboard.js?v=ccW3-dOQVW9F6TznuKPS3H3kIgCAPrmsLKpsEOnJbdw:92)
    at initDashboardDragAndDrop (tuxboard.js?v=ccW3-dOQVW9F6TznuKPS3H3kIgCAPrmsLKpsEOnJbdw:232)
    at initialize (tuxboard.js?v=ccW3-dOQVW9F6TznuKPS3H3kIgCAPrmsLKpsEOnJbdw:1168)
    at tuxboard.js?v=ccW3-dOQVW9F6TznuKPS3H3kIgCAPrmsLKpsEOnJbdw:1177
    at tuxboard.js?v=ccW3-dOQVW9F6TznuKPS3H3kIgCAPrmsLKpsEOnJbdw:1179
```
I guess the following code is not executing

```C#
<vc:tuxbar></vc:tuxbar>
<vc:tuxboard id="myDashboard" model="Model.Dashboard"></vc:tuxboard>
```

I have added tag helper in _ViewImports.cshtml

**Comment by jdanylko** [comment]
Thanks for checking it out.

The project is currently in a flux state with two projects and the UI part in two technologies: vanilla JavaScript (master branch) and TypeScript (feature/TypeScript branch).

The TypeScript branch is 99% done and working. I'm checking to see if there's anything missing.

I'm thinking about removing the UI part of the project and allow others to create their own UI part of it.

Tuxboard.Core will be NuGet'd and Tuxboard.<JSFramework> will be whatever someone is interested in building. For example, creating a Vue, Angular, Svelte, or React frontend for it.

Right now, **I would suggest grabbing the TypeScript branch**. It's more granular and manageable (and easier to follow) than the vanilla JavaScript. Let me know if this doesn't work.

I'll be updating the [Wiki](https://github.com/jdanylko/Tuxboard/wiki) after I check-in the code.

**Comment by reach2rv** [comment]
@jdanylko Thank you for quick reply. as suggested I am trying with Typescript branch and will update my progress here. A Wiki will be a great idea for anyone who wants to use this project further.

**Comment by reach2rv** [comment]
@jdanylko Hi.. Sorry to bother you. just wanted to know if there is any progress on WIKI. Also do let me know if I can be at any help.

**Comment by papyr** [comment]
Hello please dont abandon the current master - we need a UI thats the harder chunk for us backend devs, I hope I didn't misread this.

**Comment by jdanylko** [comment]
If you look at the other branch, I'm working on the TypeScript version of Tuxboard.

I understand the UI is hard, but I want to transition it to TypeScript since it's the common denominator for all JS Frameworks.

**Comment by fasteddys** [comment]
How can I view the other branch
