### ISSUE TITLE
Build Error -- 'IConfiguration' does not contain a definition for 'Get' and no accessible extension method 'Get' 

### ISSUE THREAD

**Issue by weedkiller** [jdanylko/Tuxboard#5]
I was able to update to 5.0, also I had to implement the `IConfiguration `Interface on `TuxboardConfig`

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'IConfiguration' does not contain a definition for 'Get' and no accessible extension method 'Get' accepting a first argument of type 'IConfiguration' could be found (are you missing a using directive or an assembly reference?)	Tuxboard.Core	F:\Tuxboard\Tuxboard.Core\Infrastructure\Services\DashboardService.cs	27	Active
```

**Comment by papyr** [comment]
me too it was just one error, what was your fix.. but I updated last [weeks ASP release](https://dotnet.microsoft.com/download/dotnet/6.0) of `.NET Core preview 6`

Most of it is just like 3.1 but they combined Xamarin and others into the one .NET target

**Comment by jdanylko** [comment]
Is this still an issue?
