### ISSUE TITLE
Typscript cant find Bootstrap

### ISSUE THREAD

**Issue by weedkiller** [jdanylko/Tuxboard#7]
Severity	Code	Description	Project	File	Line	Suppression State
Error	TS2307	(TS) Cannot find module 'bootstrap' or its corresponding type declarations.	Tuxboard.UI	C:\Tuxboard-feature-typescript\Tuxboard.UI\wwwroot\src\Extras\Dialogs\AddWidgetDialog\AddWidgetDialog.ts	7	Active

- [ ] Are you expecting bootstrap with NPM or with Nuget, I ran `npm install --save @types/bootstrap` For BS 5 in the Src Folder

![image](https://user-images.githubusercontent.com/21086190/109873010-2e803180-7c3b-11eb-8900-c511ba9ec3e5.png)

**Comment by jdanylko** [comment]
If you look at the libman.json in the root, I'm using the VS 2019 "Restore client-side libraries".

This will change soon because I feel the libman.json is being phased out and we'll use npm instead.

Thoughts?

**Comment by weedkiller** [comment]
Yes I agree NPM for client side is a safe bet. I thought libman was marketed as the do-all save-all, guess it didnt pan out.
